apiVersion: v1
kind: Service
metadata:
  name: "php-svc-baseline"
  labels:
    app: "php-svc-baseline"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: "php"
    azure-pipeline/version: "baseline"
