
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deploy
spec:
  replicas: 3
  selector:
      matchLabels:
        app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers: 
        - name: spring-app
          image: lottechemicalacr.azurecr.io/spring-app
          ports:
            - name: http
              containerPort: 8222
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8222
              scheme: HTTP
            initialDelaySeconds: 660
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
