apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  namespace: azdev
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-app
      vers: 22.11.29-001
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-app
#         vers: 22.11.29-001
    spec:
      containers:
      - image: lottechemicalacr.azurecr.io/spring-app
        imagePullPolicy: IfNotPresent
        name: spring-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8222
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: lottechemicalacr2257d2fa-auth
