apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment-preview
  namespace: azdev
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-app
      vers: {{SED_DATA}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-app
        vers: {{SED_DATA}}
    spec:
      containers:
      - image: lottechemicalacr.azurecr.io/spring-app:{{SED_DATA}}
        imagePullPolicy: IfNotPresent
        name: spring-app
        ports:
        - containerPort: 8222
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8222
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
      imagePullSecrets:
      - name: lottechemicalacr2257d2fa-auth
