apiVersion: v1
kind: Service
metadata: 
  name: spring-app-svc
  labels: 
    app: spring-app-svc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8222
  selector: 
    app: spring-app
    color: blue
  type: LoadBalancer
