apiVersion: v1
kind: Service
metadata: 
  name: spring-app-svc-green
  labels: 
    app: spring-app-svc-green
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8222
  selector: 
    app: spring-app
    vers: blue
  type: LoadBalancer
