name: Blue-Green-strategy
on:
  workflow_dispatch:
    inputs:
      NEW_VERSION:
        required: false
        default: "1.0"
        type: string
      OLD_VERSION:
        required: false
        default: "1.0"
        type: string
      IMAGENAME:
        required: false
        default: "php"
        type: string
      NAMESPACE:
        required: false
        default: "default"
        type: string
      BRANCH:
        required: false
        default: "default"
        type: string
jobs:
  deployapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.BRANCH }}
        
      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_kubeconfig }}
        id: login

      - uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ github.event.inputs.NAMESPACE }}
          images: |
            lottechemicalacr.azurecr.io/${{ github.event.inputs.IMAGENAME }}:${{ github.event.inputs.NEW_VERSION }}
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          strategy: blue-green
          # route-method: service # substitute with service/smi as per need
          # route-method: ingress # substitute with service/smi as per need
          # version-switch-buffer: 15
          traffic-split-method: pod
          action: deploy #deploy is the default; we will later use this to promote/reject

  approveapp:
    runs-on: ubuntu-latest
    needs: deployapp
    environment: akspromotion
    steps:
      - run: echo asked for approval joonhyeok

  promotereject:
    runs-on: ubuntu-latest
    needs: approveapp
    steps:
      - uses: actions/checkout@v2

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_kubeconfig }}
        id: login

      - name: Promote App
        uses: azure/k8s-deploy@v1.3
        if: ${{ success() }}
        with:
          namespace: ${{ github.event.inputs.NAMESPACE }}
          manifests: |
            manifests/service.yml
            manifests/deployment.yml
          images: |
            lottechemicalacr.azurecr.io/${{ github.event.inputs.IMAGENAME }}:${{ github.event.inputs.NEW_VERSION }}
          strategy: blue-green
          traffic-split-method: pod
          action: promote #deploy is the default; we will later use this to promote/reject

      - name: Reject App
        uses: azure/k8s-deploy@v1.3
        if: ${{ failure() }}
        with:
          namespace: ${{ github.event.inputs.NAMESPACE }}
          manifests: |
            manifests/service.yml
            manifests/deployment.yml
          images: |
            lottechemicalacr.azurecr.io/${{ github.event.inputs.IMAGENAME }}:${{ github.event.inputs.OLD_VERSION }}
          strategy: blue-green
          traffic-split-method: pod
          action: reject #deploy is the default; we will later use this to promote/reject
