name: Blue-Green-strategy
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        required: false
        default: "main"
        type: string
jobs:
  deployapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.BRANCH }}
  approveapp:
    runs-on: ubuntu-latest
    needs: deployapp
    environment: joon
    steps:
      - run: echo asked for approval joonhyeok
  promotereject:
    runs-on: ubuntu-latest
    needs: approveapp
    steps:
      - name: Promote App
        if: ${{ success() }}
        run: echo '승인'
      - name: Reject App
        if: ${{ failure() }}
        run: echo '거절'
