name: if test
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        required: false
        default: "main"
        type: string
jobs:
  deployapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.BRANCH }}
  approveapp:
    runs-on: ubuntu-latest
    needs: deployapp
    environment: joon
    steps:
      - run: echo '이 프로세스를 실행하고 있다'

  promotereject:
    runs-on: ubuntu-latest
    needs: approveapp
    steps:
      - name: Promote App
        if: ${{ success() }}
        run: echo '다음 프로세스~'
